version: "3.8"

services:
    backend:
        image: oven/bun:1.0.3-debian
        working_dir: /app
        volumes:
            - ./backend:/app
        command:
            - "bun"
            - "--watch"
            - "index.ts"
        ports:
            - "3000:3000"
        depends_on:
            db:
                condition:
                    service_healthy
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
            interval: 1m30s
            timeout: 10s
            retries: 3

    db:
        image: postgres:16.1-bullseye
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=123456!
            - POSTGRES_USER=db_user
            - POSTGRES_DB=db_name
        volumes:
            - ./pg-data:/var/lib/postgresql/data
            - ./migration/prisma/migrations/20240115085101_init/migration.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -h /var/run/postgresql" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./frontend/dist:/usr/share/nginx/html:ro
            - ./nginx/conf.d-compression.conf:/etc/nginx/conf.d/compression.conf:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
